/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tampilan;
import java.sql.*;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import koneksi.koneksi;

/**
 *
 * @author Athiya
 */
public class MenuUtama extends javax.swing.JFrame {
    private Connection conn = new koneksi().connect();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuUtama.class.getName());

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar4 = new javax.swing.JMenuBar();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItempelanggan = new javax.swing.JMenuItem();
        jMenuItembarang = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemkasir = new javax.swing.JMenuItem();
        jMenuItemnota = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        jlaporan = new javax.swing.JMenuItem();

        label1.setText("label1");

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("File");
        jMenuBar3.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("File");
        jMenuBar4.add(jMenu7);

        jMenu8.setText("Edit");
        jMenuBar4.add(jMenu8);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel4.setText("Sistem Aplikasi Penjualan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel5.setText("Pemrograman Visual");

        jMenu1.setText("Master");

        jMenuItempelanggan.setText("Pelanggan");
        jMenuItempelanggan.addActionListener(this::jMenuItempelangganActionPerformed);
        jMenu1.add(jMenuItempelanggan);

        jMenuItembarang.setText("Barang");
        jMenuItembarang.addActionListener(this::jMenuItembarangActionPerformed);
        jMenu1.add(jMenuItembarang);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Transaksi");

        jMenuItemkasir.setText("Kasir");
        jMenuItemkasir.addActionListener(this::jMenuItemkasirActionPerformed);
        jMenu2.add(jMenuItemkasir);

        jMenuItemnota.setText("Nota");
        jMenuItemnota.addActionListener(this::jMenuItemnotaActionPerformed);
        jMenu2.add(jMenuItemnota);

        jMenuBar1.add(jMenu2);

        jMenu9.setText("Laporan");

        jlaporan.setText("Laporan Data Pelanggan");
        jlaporan.addActionListener(this::jlaporanActionPerformed);
        jMenu9.add(jlaporan);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemkasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemkasirActionPerformed
        kasir frmK = new kasir();
        frmK.setVisible(true);
    }//GEN-LAST:event_jMenuItemkasirActionPerformed

    private void jMenuItemnotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemnotaActionPerformed
        nota frmN = new nota();
        frmN.setVisible(true);
    }//GEN-LAST:event_jMenuItemnotaActionPerformed

    private void jMenuItempelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItempelangganActionPerformed
        pelanggan frmP = new pelanggan();
        frmP.setVisible(true);
    }//GEN-LAST:event_jMenuItempelangganActionPerformed

    private void jMenuItembarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItembarangActionPerformed
        barang frmB = new barang();
        frmB.setVisible(true);
    }//GEN-LAST:event_jMenuItembarangActionPerformed

    private void jlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlaporanActionPerformed
        try {
            String path="C:/apache/Aplikasi_Penjualan/src/tampilan/LapPelanggan.jasper"; 
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path,parameter,conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane,"Dokumen Tidak Ada "+ex);
        }
    }//GEN-LAST:event_jlaporanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuBar jMenuBar4;
    private javax.swing.JMenuItem jMenuItembarang;
    private javax.swing.JMenuItem jMenuItemkasir;
    private javax.swing.JMenuItem jMenuItemnota;
    private javax.swing.JMenuItem jMenuItempelanggan;
    private javax.swing.JMenuItem jlaporan;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
